name: calculate_invoice
description: A command-line application to generate monthly invoice figures from Toggl.
version: 0.1.0

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
   http: ^0.13.3
   json_serializable: ^5.0.0
   jiffy: ^4.1.0
   equatable: ^2.0.3
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.1
  build_runner: ^2.0.6
  test: ^1.17.10
